# Generated by Django 2.2 on 2020-10-22 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('cus_id', models.IntegerField(default=None)),
                ('books_ids', models.CharField(default=None, max_length=50)),
                ('born', models.CharField(default=None, max_length=20)),
                ('day', models.DateField(default=datetime.date(2020, 10, 18))),
                ('gender', models.CharField(default=None, max_length=10)),
                ('address', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone1', models.IntegerField(default=None)),
                ('phone2', models.IntegerField(default=None)),
                ('comment', models.TextField(default=None, max_length=255)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('people', models.CharField(default=None, max_length=5)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('desc', models.TextField(default=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('max_pepl', models.IntegerField(default=None)),
                ('photo1', models.ImageField(default=None, upload_to='thumbnail')),
                ('photo2', models.ImageField(blank=True, default=None, null=True, upload_to='thumbnail')),
                ('photo3', models.ImageField(blank=True, default=None, null=True, upload_to='thumbnail')),
                ('day', models.CharField(default=None, max_length=100)),
                ('Price', models.CharField(default=None, max_length=100)),
                ('seat', models.CharField(default=None, max_length=20)),
                ('meeting', models.CharField(default=None, max_length=256)),
                ('special', models.BooleanField(default=False)),
                ('special_desc', models.TextField(blank=True, default=None, max_length=620, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking_app.Post')),
            ],
        ),
    ]
