# Generated by Django 2.2 on 2020-10-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='max_pepl',
            new_name='max_people',
        ),
    ]
