# Generated by Django 2.2 on 2020-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_auto_20201022_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name_trip',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
