# Generated by Django 2.2 on 2020-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day_go',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
