# Generated by Django 2.2 on 2020-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_booking_day_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
