# Generated by Django 2.2 on 2020-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_auto_20201022_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_av',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_sids',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
