# Generated by Django 2.2 on 2021-02-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_auto_20201022_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='trip_sids',
            new_name='trip_ids',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone2',
        ),
    ]
