# Generated by Django 2.2 on 2021-02-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_post_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AlterField(
            model_name='post',
            name='Token',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateField(default=datetime.date(2020, 10, 18)),
        ),
    ]
