# Generated by Django 2.2 on 2021-02-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_auto_20210222_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
    ]
