# Generated by Django 2.2 on 2021-02-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_auto_20210222_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='books_ids',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cus_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='day',
            new_name='day_born',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='born',
            new_name='departure_day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='meeting',
            new_name='meeting_point',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='day_go',
            new_name='place_born',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='seat_av',
            new_name='seat_available',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='trip_ids',
            new_name='trip_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='user_name',
        ),
    ]
