# Generated by Django 2.2 on 2021-02-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0015_auto_20210223_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone1',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
