# Generated by Django 2.2 on 2021-02-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0016_auto_20210227_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
