# Generated by Django 2.2 on 2021-02-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0018_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='day',
            new_name='departure_day',
        ),
    ]
