# Generated by Django 2.2 on 2021-02-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0020_auto_20210228_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Price',
            field=models.IntegerField(default=None),
        ),
    ]
