# Generated by Django 2.2 on 2021-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0021_auto_20210228_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
