# Generated by Django 2.2 on 2021-10-19 15:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0022_auto_20210228_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='JPEG', keep_meta=True, quality=75, size=[1980, 1080], upload_to='thumbnail'),
        ),
    ]
