# Generated by Django 2.2 on 2021-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0025_auto_20211019_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
