# Generated by Django 2.2 on 2021-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0026_auto_20211021_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
