# Generated by Django 2.2 on 2021-10-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0026_auto_20211021_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='booking_app.category'),
        ),
    ]
